# Basic settings
title: F+ Developer Docs
description: A site for developers showing how to implemnt the F+ API's
author:
  name: Frasers Group Financial Services
#baseurl: "/my-site" # The repository name (optional, remove if not needed)
url: "https://frasersgroup.github.io/frasersplus-developer-docs/" # Your GitHub Pages URL

# Google Analytics
google_analytics: G-HKSPFBEBQH

# Theme
remote_theme: jekyll/minima
#theme: minima # You can replace this with other supported themes

minima:
  header_pages:
    - pay.md
    - loyalty.md
    - mock-values.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown

# Plugins (optional, add more as needed)
plugins:
  - jekyll-feed # For RSS feed support
  - jekyll-seo-tag # For better SEO

# Navigation bar (Minima theme supports this)
# Add links to other pages on your site or external sites
navbar:
  - title: "Home"
    url: /
  - title: "Pay"
    url: /pay/
  - title: "Loyalty"
    url: /loyalty/

header_pages:
  - pay.md
  - loyalty.md

# Social media links (used with themes that support it)
#social_links:
#  twitter: your_twitter_handle
#  github: yourusername
#  linkedin: your-linkedin-profile

# Exclude certain files or folders from being included in the site
exclude:
  - README.md
  - LICENSE

# Enable pagination for blog posts (if you have a _posts folder)
#paginate: 5
#paginate_path: "/blog/page:num/"

# Deployment settings
# Uncomment and configure if using a custom domain
custom_domain: "developer.frasersplus.com"
