# Basic settings
title: F+ Developer Docs
description: A site for developers showing how to implement the F+ API's
author: Frasers Group Financial Services
#baseurl: "/my-site" # The repository name (optional, remove if not needed)
url: "https://frasersgroup.github.io/frasersplus-developer-docs/" # Your GitHub Pages URL

# Theme
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
theme: minima # You can replace this with other supported themes

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown

# Navigation bar (Minima theme supports this)
# Add links to other pages on your site or external sites
nav:
  - title: "Home"
    url: /
  - title: "Pay"
    url: /pay/
  - title: "Loyalty"
    url: /loyalty/

# Exclude certain files or folders from being included in the site
exclude:
  - README.md
  - LICENSE

# Enable pagination for blog posts (if you have a `_posts` folder)
paginate: 5
paginate_path: "/blog/page:num/"

# Deployment settings
# Uncomment and configure if using a custom domain
custom_domain: "developer.frasersplus.com"
